name: pokemon_transforms
version: '1.0.0'
config-version: 2
profile: pokemon_dbt

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  pokemon_transforms:
    staging:
      +materialized: view
      +schema: raw_data
    intermediate:
      +materialized: table
    marts:
      +materialized: table