name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install project dependencies
        run: just install

      - name: Install prek
        run: uv tool install prek

      - name: Run prek checks on all files
        run: uv run prek run --all-files
